/**
 * 100 unique emoticons for the feelings game. Each maps to one kid-friendly label;
 * three-choice rounds pick two distractors from EMOTION_WORD_POOL.
 */
export type EmotionRoundDef = {
  face: string;
  correct: string;
};

export const EMOTION_ROUND_DEFS: EmotionRoundDef[] = [
  { face: '😀', correct: 'Grinning' },
  { face: '😃', correct: 'Beaming' },
  { face: '😄', correct: 'Joyful' },
  { face: '😁', correct: 'Happy' },
  { face: '😆', correct: 'Laughing' },
  { face: '🥹', correct: 'Touched' },
  { face: '😅', correct: 'Relieved' },
  { face: '🤣', correct: 'Cracking up' },
  { face: '😂', correct: 'Giggly' },
  { face: '🙂', correct: 'Pleasant' },
  { face: '🙃', correct: 'Silly' },
  { face: '😉', correct: 'Playful' },
  { face: '😊', correct: 'Kind' },
  { face: '😇', correct: 'Peaceful' },
  { face: '🥰', correct: 'Loving' },
  { face: '😍', correct: 'Adoring' },
  { face: '🤩', correct: 'Starstruck' },
  { face: '😘', correct: 'Kissy' },
  { face: '😗', correct: 'Sweet' },
  { face: '☺️', correct: 'Calm' },
  { face: '😚', correct: 'Shy' },
  { face: '😙', correct: 'Caring' },
  { face: '🥲', correct: 'Tearful' },
  { face: '😋', correct: 'Mischief' },
  { face: '😛', correct: 'Teasing' },
  { face: '😜', correct: 'Goofy' },
  { face: '🤪', correct: 'Wild' },
  { face: '😝', correct: 'Silly' },
  { face: '🤑', correct: 'Silly' },
  { face: '🤗', correct: 'Huggy' },
  { face: '🤭', correct: 'Bashful' },
  { face: '🫢', correct: 'Surprised' },
  { face: '🫣', correct: 'Peeky' },
  { face: '🤫', correct: 'Quiet' },
  { face: '🤔', correct: 'Thoughtful' },
  { face: '🫡', correct: 'Proud' },
  { face: '🤐', correct: 'Quiet' },
  { face: '🤨', correct: 'Skeptical' },
  { face: '😐', correct: 'Serious' },
  { face: '😑', correct: 'Blank' },
  { face: '😶', correct: 'Quiet' },
  { face: '😏', correct: 'Smug' },
  { face: '😒', correct: 'Annoyed' },
  { face: '🙄', correct: 'Bored' },
  { face: '😬', correct: 'Nervous' },
  { face: '🤥', correct: 'Unsure' },
  { face: '😌', correct: 'Relaxed' },
  { face: '😔', correct: 'Down' },
  { face: '😪', correct: 'Sleepy' },
  { face: '🤤', correct: 'Dreamy' },
  { face: '😴', correct: 'Tired' },
  { face: '😷', correct: 'Sick' },
  { face: '🤒', correct: 'Ill' },
  { face: '🤕', correct: 'Hurt' },
  { face: '🤢', correct: 'Sick' },
  { face: '🤮', correct: 'Sick' },
  { face: '🤧', correct: 'Sniffly' },
  { face: '🥵', correct: 'Hot' },
  { face: '🥶', correct: 'Cold' },
  { face: '🥴', correct: 'Dizzy' },
  { face: '😵', correct: 'Dizzy' },
  { face: '🤯', correct: 'Amazed' },
  { face: '🤠', correct: 'Playful' },
  { face: '🥳', correct: 'Celebrating' },
  { face: '🥸', correct: 'Goofy' },
  { face: '😎', correct: 'Cool' },
  { face: '🤓', correct: 'Studious' },
  { face: '🧐', correct: 'Curious' },
  { face: '😕', correct: 'Worried' },
  { face: '🫤', correct: 'Unsure' },
  { face: '😟', correct: 'Sad' },
  { face: '🙁', correct: 'Worried' },
  { face: '☹️', correct: 'Upset' },
  { face: '😮', correct: 'Surprised' },
  { face: '😯', correct: 'Surprised' },
  { face: '😲', correct: 'Shocked' },
  { face: '😳', correct: 'Embarrassed' },
  { face: '🥺', correct: 'Pleading' },
  { face: '😦', correct: 'Scared' },
  { face: '😧', correct: 'Scared' },
  { face: '😨', correct: 'Scared' },
  { face: '😰', correct: 'Nervous' },
  { face: '😥', correct: 'Sad' },
  { face: '😢', correct: 'Crying' },
  { face: '😭', correct: 'Upset' },
  { face: '😱', correct: 'Frightened' },
  { face: '😖', correct: 'Frustrated' },
  { face: '😣', correct: 'Tired' },
  { face: '😞', correct: 'Disappointed' },
  { face: '😓', correct: 'Worried' },
  { face: '😩', correct: 'Weary' },
  { face: '😫', correct: 'Tired' },
  { face: '🥱', correct: 'Sleepy' },
  { face: '😤', correct: 'Frustrated' },
  { face: '😡', correct: 'Angry' },
  { face: '😠', correct: 'Angry' },
  { face: '🤬', correct: 'Angry' },
  { face: '😈', correct: 'Mischief' },
  { face: '👿', correct: 'Grumpy' },
  { face: '💀', correct: 'Spooked' },
];

/** Every label used above, plus extras so distractors stay varied */
export const EMOTION_WORD_POOL: string[] = Array.from(
  new Set([
    ...EMOTION_ROUND_DEFS.map((d) => d.correct),
    'Hopeful',
    'Lonely',
    'Brave',
    'Thankful',
    'Gentle',
    'Patient',
    'Polite',
    'Excited',
    'Confused',
    'Cheerful',
  ])
);
