/**
 * Offline sentence bank — expand anytime. No network or AI required at runtime.
 * Tier 1: very short. Tier 2: medium. Tier 3: longer / richer.
 */
export type ReadTier = 1 | 2 | 3;

export type ReadSentence = {
  text: string;
  tier: ReadTier;
};

export const READ_SENTENCES: readonly ReadSentence[] = [
  { text: 'The sun is warm.', tier: 1 },
  { text: 'I see a bird.', tier: 1 },
  { text: 'We read a book.', tier: 1 },
  { text: 'The cat is soft.', tier: 1 },
  { text: 'I like soup.', tier: 1 },
  { text: 'Stars shine at night.', tier: 1 },
  { text: 'We walk in the park.', tier: 1 },
  { text: 'The moon is bright.', tier: 1 },
  { text: 'I hear the rain.', tier: 1 },
  { text: 'Friends play together.', tier: 1 },
  { text: 'The tree is tall.', tier: 1 },
  { text: 'I draw with a pencil.', tier: 1 },
  { text: 'The dog wags its tail.', tier: 1 },
  { text: 'We share our snacks.', tier: 1 },
  { text: 'The flower opens slow.', tier: 1 },
  { text: 'I zip my coat.', tier: 1 },
  { text: 'The bus stops here.', tier: 1 },
  { text: 'We plant a seed.', tier: 1 },
  { text: 'The kite flies high.', tier: 1 },
  { text: 'I brush my teeth.', tier: 1 },
  { text: 'My hat is blue.', tier: 1 },
  { text: 'The ball rolls fast.', tier: 1 },
  { text: 'We sing a song.', tier: 1 },
  { text: 'The baby sleeps.', tier: 1 },
  { text: 'I find a shell.', tier: 1 },
  { text: 'The bell rings loud.', tier: 1 },
  { text: 'We wash our hands.', tier: 1 },
  { text: 'The car is red.', tier: 1 },
  { text: 'I love my mom.', tier: 1 },
  { text: 'The fish swims.', tier: 1 },
  { text: 'We build a fort.', tier: 1 },
  { text: 'The door is open.', tier: 1 },
  { text: 'I taste honey.', tier: 1 },
  { text: 'The duck says quack.', tier: 1 },
  { text: 'We hop on one foot.', tier: 1 },
  { text: 'The cup is full.', tier: 1 },
  { text: 'I wave hello.', tier: 1 },
  { text: 'The barn is red.', tier: 1 },
  { text: 'We mix the paint.', tier: 1 },
  { text: 'The bee is busy.', tier: 1 },
  { text: 'I wear warm socks.', tier: 1 },
  { text: 'The ship sails by.', tier: 1 },
  { text: 'We feed the hens.', tier: 1 },
  { text: 'The lamp glows soft.', tier: 1 },
  { text: 'I find a coin.', tier: 1 },
  { text: 'The drum goes boom.', tier: 1 },
  { text: 'We rake the leaves.', tier: 1 },
  { text: 'The nest is small.', tier: 1 },
  { text: 'I sip cool juice.', tier: 1 },
  { text: 'The goat chews hay.', tier: 1 },
  { text: 'We line up neatly.', tier: 1 },
  { text: 'The rope swings.', tier: 1 },
  { text: 'I spot a star.', tier: 1 },

  { text: 'The ocean waves are gentle today.', tier: 2 },
  { text: 'A quiet room helps me think clearly.', tier: 2 },
  { text: 'We count the steps up the hill.', tier: 2 },
  { text: 'The library smells like paper and calm.', tier: 2 },
  { text: 'My blanket feels cozy after school.', tier: 2 },
  { text: 'The baker mixes flour and hope.', tier: 2 },
  { text: 'We watch the clouds change shape.', tier: 2 },
  { text: 'The frog hops from stone to stone.', tier: 2 },
  { text: 'I whisper thank you to the nurse.', tier: 2 },
  { text: 'The train hums along the track.', tier: 2 },
  { text: 'We fold the map with care.', tier: 2 },
  { text: 'The clock ticks in the hallway.', tier: 2 },
  { text: 'I pack a lunch with fruit and love.', tier: 2 },
  { text: 'The river bends around the rocks.', tier: 2 },
  { text: 'We spot a hawk above the field.', tier: 2 },
  { text: 'The paint dries on my picture.', tier: 2 },
  { text: 'I tie my shoes in double knots.', tier: 2 },
  { text: 'The campfire pops and glows.', tier: 2 },
  { text: 'We listen before we answer.', tier: 2 },
  { text: 'The snowflake melts on my glove.', tier: 2 },
  { text: 'The scooter glides down the smooth sidewalk.', tier: 2 },
  { text: 'We stack blocks until the tower wobbles and giggles.', tier: 2 },
  { text: 'The librarian stamps the date with a cheerful thump.', tier: 2 },
  { text: 'I peel an orange and the smell fills the kitchen.', tier: 2 },
  { text: 'The puppy learns to sit for a tiny treat.', tier: 2 },
  { text: 'We follow footprints in the damp sand.', tier: 2 },
  { text: 'The kettle whistles when the water is ready.', tier: 2 },
  { text: 'I braid my hair while humming a soft tune.', tier: 2 },
  { text: 'The spider weaves a web between two leaves.', tier: 2 },
  { text: 'We pass notes of encouragement under the desk.', tier: 2 },
  { text: 'The violin sings a slow, careful scale.', tier: 2 },
  { text: 'I water the herbs on the sunny windowsill.', tier: 2 },
  { text: 'The crow watches us from the fence post.', tier: 2 },
  { text: 'We sketch the skyline before the sun goes down.', tier: 2 },
  { text: 'The boots leave muddy prints on the mat.', tier: 2 },
  { text: 'I tighten the loose screw on my toy car.', tier: 2 },
  { text: 'The wind chimes answer each other in the breeze.', tier: 2 },
  { text: 'We share headphones and listen to one story.', tier: 2 },
  { text: 'The baker sprinkles sugar like tiny stars.', tier: 2 },
  { text: 'I copy the letters until they feel steady.', tier: 2 },
  { text: 'The squirrel buries a nut beside the path.', tier: 2 },
  { text: 'We roll the dice and move our game piece.', tier: 2 },
  { text: 'The rain taps the roof in a steady rhythm.', tier: 2 },
  { text: 'I polish my shoes until they shine.', tier: 2 },
  { text: 'The owl hoots once from the tall pine.', tier: 2 },
  { text: 'We tape the torn page back into the book.', tier: 2 },
  { text: 'The swing arcs high over the clover.', tier: 2 },
  { text: 'I measure flour with a level scoop.', tier: 2 },
  { text: 'The ferry horn echoes across the harbor.', tier: 2 },
  { text: 'We label our jars so soup night is easy.', tier: 2 },
  { text: 'The hedgehog hides under a pile of leaves.', tier: 2 },
  { text: 'I practice the scale on a borrowed flute.', tier: 2 },
  { text: 'The tractor pulls a wagon full of pumpkins.', tier: 2 },
  { text: 'We toast marshmallows until they turn golden.', tier: 2 },
  { text: 'The chalk leaves dusty rainbows on the pavement.', tier: 2 },

  { text: 'When the wind picks up, we hold our hats and laugh anyway.', tier: 3 },
  { text: 'Grandma saves stories in a tin box under the window seat.', tier: 3 },
  { text: 'The lighthouse blinks hello to every passing boat.', tier: 3 },
  { text: 'We measure kindness in small, patient moments.', tier: 3 },
  { text: 'The orchestra tunes until the room feels electric and soft.', tier: 3 },
  { text: 'I practice new words until they feel like old friends.', tier: 3 },
  { text: 'The garden teaches that growth takes sun and steady water.', tier: 3 },
  { text: 'Under the bridge, the echo answers in a friendly voice.', tier: 3 },
  { text: 'We write a letter even when the stamp is crooked.', tier: 3 },
  { text: 'The mountain looks far until we take the first step.', tier: 3 },
  { text: 'A good question opens more doors than a loud shout.', tier: 3 },
  { text: 'The bakery opens early, and the street smells like morning.', tier: 3 },
  { text: 'We mend the kite string and try the hill again.', tier: 3 },
  { text: 'The telescope shows that tiny dots can be worlds.', tier: 3 },
  { text: 'I read aloud because stories like company.', tier: 3 },
  { text: 'The river carries leaves like tiny boats with no map.', tier: 3 },
  { text: 'We thank the bus driver for a smooth, careful ride.', tier: 3 },
  { text: 'The puzzle waits on the table, patient and full of corners.', tier: 3 },
  { text: 'When words feel tricky, we slow down and breathe between them.', tier: 3 },
  { text: 'The old map smelled like cedar and adventures we had not taken yet.', tier: 3 },
  { text: 'We promised to meet at the bench where the lilacs lean toward the path.', tier: 3 },
  { text: 'The violinist tuned quietly while the audience held its breath.', tier: 3 },
  { text: 'I learned that courage can sound like a small, clear yes.', tier: 3 },
  { text: 'The tide pulled shells back into the swirling, patient blue.', tier: 3 },
  { text: 'We wrote our names in the frost and watched them shimmer and fade.', tier: 3 },
  { text: 'The clock in the hall remembers every hurried morning.', tier: 3 },
  { text: 'A handwritten recipe is a love letter with measurements.', tier: 3 },
  { text: 'The fox paused, ears forward, then slipped into the tall grass.', tier: 3 },
  { text: 'We carried the cake up three flights and did not drop a crumb.', tier: 3 },
  { text: 'The telescope showed Saturn wearing its thin, icy rings.', tier: 3 },
  { text: 'I forgave the rainy day when I saw the rainbow arch the hill.', tier: 3 },
  { text: 'The choir rose note by note until the room felt like sunlight.', tier: 3 },
  { text: 'We planted milkweed so the monarchs would have a place to rest.', tier: 3 },
  { text: 'The ferry rocked gently, and gulls argued over the wake.', tier: 3 },
  { text: 'My compass needle trembled, then pointed toward honest north.', tier: 3 },
  { text: 'The attic held trunks full of buttons, ribbons, and quiet stories.', tier: 3 },
  { text: 'We measured the tree’s shadow and guessed how tall it had grown.', tier: 3 },
  { text: 'The baker apologized with warm cinnamon rolls and a grin.', tier: 3 },
  { text: 'I practiced the speech in front of the bathroom mirror first.', tier: 3 },
  { text: 'The glacier cracked like a distant door opening to cold blue rooms.', tier: 3 },
  { text: 'We followed fireflies until the meadow felt like a jar of stars.', tier: 3 },
  { text: 'The librarian slid a worn novel across the desk like a secret.', tier: 3 },
  { text: 'Honesty does not always arrive loudly; sometimes it whispers.', tier: 3 },
  { text: 'The kite string hummed, and the wind tugged like an eager friend.', tier: 3 },
  { text: 'We stacked stones at the trailhead and promised to return in spring.', tier: 3 },
  { text: 'The cello’s low note settled into my ribs like a kind hand.', tier: 3 },
  { text: 'I mixed too much blue, but the sky forgave me on the canvas.', tier: 3 },
  { text: 'The heron stood still as a thought above the shallow pond.', tier: 3 },
  { text: 'We memorized constellations until the dark felt less empty.', tier: 3 },
  { text: 'The bread rose overnight, patient under a flour-dusted cloth.', tier: 3 },
  { text: 'Kindness repeated becomes a habit brighter than any medal.', tier: 3 },
  { text: 'The train curved along the coast, and spray dotted the windows.', tier: 3 },
  { text: 'We left pebbles stacked on the cairn for the next traveler.', tier: 3 },
  { text: 'The echo in the canyon answered with my own brave voice.', tier: 3 },
] as const;

export function maxTierForLevel(level: number): ReadTier {
  if (level >= 50) return 3;
  if (level >= 20) return 2;
  return 1;
}

/** All sentence strings available at this level (tier-filtered), for shuffle-without-repeat. */
export function readSentencesForLevel(level: number): readonly string[] {
  const maxTier = maxTierForLevel(level);
  return READ_SENTENCES.filter((s) => s.tier <= maxTier).map((s) => s.text);
}

export function pickReadSentence(level: number, exclude: string | null): string {
  const pool = readSentencesForLevel(level).filter((t) => t !== exclude);
  const list = pool.length > 0 ? pool : readSentencesForLevel(level);
  return list[Math.floor(Math.random() * list.length)]!;
}
