/** Short, friendly words for listen-and-repeat practice (100+ unique, shuffled without repeat per cycle). */
export const ECHO_WORD_POOL: readonly string[] = [
  'happy',
  'sunny',
  'bubble',
  'garden',
  'purple',
  'kitten',
  'smile',
  'pillow',
  'friend',
  'little',
  'yellow',
  'dancing',
  'cookie',
  'morning',
  'story',
  'water',
  'flower',
  'rabbit',
  'gentle',
  'wonder',
  'sparkle',
  'butterfly',
  'together',
  'quiet',
  'cozy',
  'dream',
  'ocean',
  'starlight',
  'hello',
  'goodbye',
  'apple',
  'banana',
  'cherry',
  'clever',
  'puzzle',
  'ribbon',
  'picnic',
  'ladder',
  'blanket',
  'candle',
  'dragon',
  'elephant',
  'forest',
  'guitar',
  'hammer',
  'island',
  'jacket',
  'kettle',
  'lemon',
  'magnet',
  'napkin',
  'orange',
  'pencil',
  'quilt',
  'rocket',
  'silver',
  'tunnel',
  'umbrella',
  'violin',
  'window',
  'caramel',
  'zigzag',
  'adventure',
  'balance',
  'courage',
  'dolphin',
  'enchant',
  'feather',
  'glisten',
  'harmony',
  'imagine',
  'journey',
  'kindness',
  'lullaby',
  'meadow',
  'nestled',
  'octopus',
  'painter',
  'quiver',
  'rainbow',
  'shimmer',
  'treasure',
  'unicorn',
  'whisper',
  'blossom',
  'cricket',
  'diamond',
  'emerald',
  'freckle',
  'glimmer',
  'honey',
  'icicle',
  'jasmine',
  'kingdom',
  'lantern',
  'marble',
  'nectar',
  'orchard',
  'pebble',
  'quaint',
  'ripple',
  'sunbeam',
  'twinkle',
  'velvety',
  'willow',
  'zephyr',
  'bravery',
  'crystal',
  'dazzle',
  'earnest',
  'fiddle',
  'giggle',
  'harvest',
  'inspire',
  'jolly',
  'kindred',
  'laughter',
  'mellow',
  'nimble',
  'opal',
  'prairie',
  'quokka',
  'radiant',
  'splendid',
  'tender',
  'uplift',
  'vivid',
  'wonderful',
  'yearn',
  'zinnia',
] as const;

export type RhymeRound = {
  /** Spoken cue — the child finds another word that rhymes with this. */
  prompt: string;
  /** The rhyming choice */
  correct: string;
  /** Two words that do not rhyme with prompt */
  distractors: readonly [string, string];
};

export const RHYME_ROUNDS: readonly RhymeRound[] = [
  { prompt: 'cat', correct: 'hat', distractors: ['cup', 'sun'] },
  { prompt: 'tree', correct: 'bee', distractors: ['car', 'book'] },
  { prompt: 'moon', correct: 'spoon', distractors: ['lamp', 'chair'] },
  { prompt: 'star', correct: 'car', distractors: ['dog', 'leaf'] },
  { prompt: 'boat', correct: 'coat', distractors: ['duck', 'pen'] },
  { prompt: 'king', correct: 'ring', distractors: ['ball', 'milk'] },
  { prompt: 'rain', correct: 'train', distractors: ['sock', 'desk'] },
  { prompt: 'fox', correct: 'box', distractors: ['pig', 'nest'] },
  { prompt: 'cake', correct: 'lake', distractors: ['frog', 'shoe'] },
  { prompt: 'light', correct: 'night', distractors: ['grass', 'clock'] },
  { prompt: 'bear', correct: 'chair', distractors: ['fish', 'cloud'] },
  { prompt: 'snail', correct: 'pail', distractors: ['mouse', 'road'] },
  { prompt: 'hen', correct: 'pen', distractors: ['cow', 'sky'] },
  { prompt: 'shell', correct: 'bell', distractors: ['rock', 'field'] },
  { prompt: 'play', correct: 'day', distractors: ['snow', 'brick'] },
  { prompt: 'fun', correct: 'sun', distractors: ['leg', 'table'] },
  { prompt: 'hop', correct: 'top', distractors: ['bed', 'wheel'] },
  { prompt: 'blue', correct: 'shoe', distractors: ['red', 'apple'] },
  { prompt: 'cold', correct: 'gold', distractors: ['warm', 'paper'] },
] as const;
